import type { Question } from "$lib/types/quiz";

export const questions: Question[] = [
  {
    id: "q1",
    question: "What is the capital of Australia?",
    options: ["Sydney", "Canberra", "Melbourne", "Brisbane"],
    answer: "Canberra",
    type: "mcq",
  },
  {
    id: "q2",
    question: "The chemical symbol for Gold is Au.",
    options: ["True", "False"],
    answer: "True",
    type: "true-false",
  },
  {
    id: "q3",
    question: "Who developed the theory of general relativity?",
    options: ["Isaac Newton", "Albert Einstein", "Niels Bohr", "Galileo Galilei"],
    answer: "Albert Einstein",
    type: "mcq",
  },
  {
    id: "q4",
    question: "In which year did World War II end?",
    options: ["1942", "1945", "1948", "1950"],
    answer: "1945",
    type: "mcq",
  },
  {
    id: "q5",
    question: "Water boils at 100°C at sea level.",
    options: ["True", "False"],
    answer: "True",
    type: "true-false",
  },
  {
    id: "q6",
    question: "What is the square root of 144?",
    options: ["10", "12", "14", "16"],
    answer: "12",
    type: "mcq",
  },
  {
    id: "q7",
    question: "The Great Wall of China is visible from space.",
    options: ["True", "False"],
    answer: "False",
    type: "true-false",
  },
  {
    id: "q8",
    question: "Who painted the Mona Lisa?",
    options: ["Michelangelo", "Leonardo da Vinci", "Raphael", "Donatello"],
    answer: "Leonardo da Vinci",
    type: "mcq",
  },
  {
    id: "q9",
    question: "What is the hardest natural substance on Earth?",
    options: ["Diamond", "Gold", "Quartz", "Graphite"],
    answer: "Diamond",
    type: "mcq",
  },
  {
    id: "q10",
    question: "The currency of Japan is the Yen.",
    options: ["True", "False"],
    answer: "True",
    type: "true-false",
  },
  {
    id: "q11",
    question: "What gas do plants absorb during photosynthesis?",
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
    answer: "Carbon Dioxide",
    type: "mcq",
  },
  {
    id: "q12",
    question: "The human body has four lungs.",
    options: ["True", "False"],
    answer: "False",
    type: "true-false",
  },
  {
    id: "q13",
    question: "What is the chemical formula for table salt?",
    options: ["NaCl", "KCl", "Na2CO3", "CaCl2"],
    answer: "NaCl",
    type: "mcq",
  },
  {
    id: "q14",
    question: "What is the tallest mountain in the world?",
    options: ["Mount Kilimanjaro", "Mount Everest", "K2", "Denali"],
    answer: "Mount Everest",
    type: "mcq",
  },
  {
    id: "q15",
    question: "The speed of light is approximately 300,000 km/s.",
    options: ["True", "False"],
    answer: "True",
    type: "true-false",
  },
  {
    id: "q16",
    question: "What is the smallest prime number?",
    options: ["0", "1", "2", "3"],
    answer: "2",
    type: "mcq",
  },
  {
    id: "q17",
    question: "Which organ in the human body produces insulin?",
    options: ["Pancreas", "Liver", "Kidney", "Heart"],
    answer: "Pancreas",
    type: "mcq",
  },
  {
    id: "q18",
    question: "Flashcard: Capital of Canada?",
    answer: "Ottawa",
    type: "flashcard",
  },
  {
    id: "q19",
    question: "Flashcard: Who wrote '1984'?",
    answer: "George Orwell",
    type: "flashcard",
  },
  {
    id: "q20",
    question: "Flashcard: What is the chemical symbol for Oxygen?",
    answer: "O",
    type: "flashcard",
  },
];
